### ISSUE TITLE
Midnight update issue

### ISSUE THREAD

**Issue by elden1337** [elden1337/hass-peaqnext#5]
At midnight, prices arent properly recalculated, resulting in "tomorrow" still being valid and thus showing wrong prices

**Comment by elden1337** [comment]
Reopened. Not fixed as expected in 0.1.3

**Comment by sjoukebakker** [comment]
I don't know if it helps you in finding a solution, but to troubleshoot I put `{model.idx}` in the `async_make_hours_display` function. And these values all seem to be 24 hours too high?
![Screenshot from 2023-08-01 21-29-31](https://github.com/elden1337/hass-peaqnext/assets/50876518/c347f31a-fe3f-4b5c-b5e6-5eca3c59285d)

**Comment by elden1337** [comment]
Thanks!
When i made this quicker integration i hasted a bit (since i made it for myself first and foremost) and made an overcomplicated and stupid handling of the list of occasions. 

That will be rewritten similar to my larger and more stable integrations (peaqev and peaqhvac) with proper datetimeobjects to prevent this behavior.

**Comment by sjoukebakker** [comment]
Now I think of it.. These values are probably correct. Current day 23 hour idx is 23.

**Comment by elden1337** [comment]
Ah you might be right. Possibly just a frontend-issue with formatting

**Comment by sjoukebakker** [comment]
This has not changed since yesterday evening. Also sorting seems to be wrong. It does not sort by prices, but also not by hour?
![Schermafbeelding 2023-08-03 093834](https://github.com/elden1337/hass-peaqnext/assets/50876518/bd67a3db-0388-4560-bb37-269ac7da8de1)

Maybe it would be an idea to hourly remove all earlier hours? So we only have 'future' hours in the attributes.

Another thought. I can't set my dishwasher to a specific time. There is a button for +1 hour. But that means if I activate the machine at 18:45 it will start at 23:45 for example. So only 15 minutes in that cheap hour. It would be more accurate to create a model that calculates the prices based on minutes instead of hours. But this probably requires a rewrite of your entire model. What I would like to see for my dishwasher is a attribute that tells me the amount of hours I should delay the start (like +6).

And lastly: I know the pattern of my appliance in watts. Maybe an option for a custom pattern would be possible. To make the calculation of the price more accurate.

Sorry to put all this in one issue, but I'll leave it up to you if you want to implement this.

**Comment by elden1337** [comment]
Back at it again then... 😵‍💫😁
Saw the issue myself just now with it not updating at all at times. 

The sorting might be correct, it sorts by a comparer (total cost rounded to one dec) and then by starttime. 

I will make new features out of the secondary comments.

**Comment by elden1337** [comment]
Afk so deployed quickly on mobile. 0.2.1 at least works fine for me with over night and passed hours. 

Please close this issue if you agree @sjoukebakker

**Comment by sjoukebakker** [comment]
Thanks, great. 👍 I think it works. Maybe it's a good idea to wait with closing the issue until this afternoon (when tomorrows prices become available) and tomorrow (after midnight update) to be sure it works correctly. 

Rounding to one decimal makes the data quite useless in my case because that allows a difference of 0.09 EUR (1.05 SEK) . My hourly prices are also in that range today (cheapest hour is 0.285 and most expensive 0.377). So in my case it basically sorts by hour right now.

Maybe the current hour can also be removed from the list. Now it will display starting at 10:00 as the cheapest option, even when it is already 10:59.

**Comment by elden1337** [comment]
I think the comparer perhaps could be improved by adding one decimal if using cent. Lets look in another issue

**Comment by sjoukebakker** [comment]
It works! I can't close the issue I think. I did not open this issue.
